import { CfnOutput, Duration, RemovalPolicy, Stack, StackProps } from 'aws-cdk-lib';
import { ISecurityGroup, IVpc, SubnetType } from 'aws-cdk-lib/aws-ec2';
import { Credentials, DatabaseInstance, DatabaseInstanceEngine, StorageType } from 'aws-cdk-lib/aws-rds';
import { ISecret, Secret } from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

import { EnvironmentConfig } from '../config/types';
import { applyPlatformTags } from '../tags';

export interface DatabaseStackProps extends StackProps {
  /** Environment specific configuration. No environment value is hardcoded in this stack. */
  readonly config: EnvironmentConfig;

  /** The Phase 1 VPC. The instance lands in its isolated database subnets. */
  readonly vpc: IVpc;

  /**
   * The Phase 1 database security group. It already accepts TCP 5432 from the application security
   * group and from nothing else, so this stack adds no rule of its own: it only attaches the group
   * to the instance. That keeps every security group rule in one place, in the stack that owns the
   * groups.
   */
  readonly databaseSecurityGroup: ISecurityGroup;
}

/**
 * Phase 3 data tier: a private, encrypted, backed up RDS PostgreSQL instance.
 *
 * ```
 *   ECS task (application SG) ──TCP 5432──▶ RDS instance (database SG)
 *                                              isolated subnets, no route off the VPC
 * ```
 *
 * The instance is not reachable from the internet, from the load balancer or from anything that
 * does not carry the application security group, and it sits in subnets with no outbound route at
 * all. It is a separate stack from the compute that uses it because it has a completely different
 * lifecycle: the application is replaced on every deployment, the database outlives it.
 *
 * The master password is generated by Secrets Manager, never written into source, the template or
 * the repository, and the application never sees it as a value it has to store: ECS injects it into
 * the container at startup from the secret this stack exports.
 */
export class DatabaseStack extends Stack {
  /** The PostgreSQL instance. */
  public readonly instance: DatabaseInstance;

  /** The database security group carried by the instance. */
  public readonly securityGroup: ISecurityGroup;

  /**
   * Secret holding the master credentials. The application stack grants its ECS execution role read
   * access to this secret and injects `username`/`password` from it into the container.
   */
  public readonly credentialsSecret: ISecret;

  constructor(scope: Construct, id: string, props: DatabaseStackProps) {
    super(scope, id, props);

    const { config, vpc, databaseSecurityGroup } = props;
    const { database } = config;
    const namePrefix = `ecommerce-${config.environment}`;

    this.securityGroup = databaseSecurityGroup;
    this.credentialsSecret = this.createCredentialsSecret(namePrefix, config);

    this.instance = new DatabaseInstance(this, 'Instance', {
      instanceIdentifier: `${namePrefix}-db`,
      engine: DatabaseInstanceEngine.postgres({ version: database.engineVersion }),
      vpc,
      // Isolated subnets only: no route to the internet gateway and none to a NAT Gateway either.
      vpcSubnets: { subnetType: SubnetType.PRIVATE_ISOLATED },
      securityGroups: [databaseSecurityGroup],
      // `fromSecret` passes the user name as a plain string and only the password as a dynamic
      // reference, so rotating the secret later does not replace the instance.
      credentials: Credentials.fromSecret(this.credentialsSecret, database.masterUsername),
      databaseName: database.databaseName,
      instanceType: database.instanceType,
      allocatedStorage: database.allocatedStorageGb,
      storageType: StorageType.GP3,
      // Encrypted with the RDS managed KMS key. Encryption at rest is not optional and is not
      // configurable per environment: an unencrypted database is a finding, not a cost saving.
      storageEncrypted: true,
      multiAz: database.multiAz,
      // Belt and braces: the instance already sits in subnets with no route off the VPC, and this
      // makes "not reachable from the internet" a property of the instance as well as the network.
      publiclyAccessible: false,
      backupRetention: Duration.days(database.backupRetentionDays),
      // Keep the automated backups wherever the instance itself is kept. Deleting them in dev is
      // what makes `cdk destroy` leave nothing behind; deleting them in uat/prod would throw away
      // the recovery window along with the instance.
      deleteAutomatedBackups: database.removalPolicy === RemovalPolicy.DESTROY,
      deletionProtection: database.deletionProtection,
      removalPolicy: database.removalPolicy,
    });

    applyPlatformTags(this, config);
    this.createOutputs(config, namePrefix);
  }

  /**
   * The master credentials, generated by Secrets Manager at deploy time.
   *
   * `generateSecretString` is resolved by CloudFormation when the stack is deployed, so the
   * password never appears in the template, in source control or in a terminal. The secret is
   * created without an explicit name: CloudFormation generates one, which means destroying and
   * recreating an environment never collides with a secret that is still inside its recovery
   * window. The secret is found by its `Project`/`Environment` tags and its exported ARN.
   */
  private createCredentialsSecret(namePrefix: string, config: EnvironmentConfig): ISecret {
    return new Secret(this, 'Credentials', {
      description: `Master credentials for the ${namePrefix} PostgreSQL database`,
      generateSecretString: {
        // The user name is fixed and the password is generated; the instance only ever reads the
        // `password` field from the secret.
        secretStringTemplate: JSON.stringify({ username: config.database.masterUsername }),
        generateStringKey: 'password',
        // Punctuation is excluded so the generated password is safe to paste into a client or a
        // JDBC URL by hand when debugging, without a quoting surprise.
        excludePunctuation: true,
        passwordLength: 30,
      },
      removalPolicy: config.database.removalPolicy,
    });
  }

  /**
   * Publishes the connection details the application stack injects into the container. The secret
   * ARN is an identifier, not a credential: the value it points at is never exported.
   */
  private createOutputs(config: EnvironmentConfig, namePrefix: string): void {
    const exportPrefix = `ecommerce-${config.environment}`;

    new CfnOutput(this, 'DatabaseEndpoint', {
      value: this.instance.dbInstanceEndpointAddress,
      description: 'Host name of the RDS PostgreSQL instance',
      exportName: `${exportPrefix}-db-endpoint`,
    });

    new CfnOutput(this, 'DatabasePort', {
      value: this.instance.dbInstanceEndpointPort,
      description: 'Port the RDS PostgreSQL instance listens on',
      exportName: `${exportPrefix}-db-port`,
    });

    new CfnOutput(this, 'DatabaseName', {
      value: config.database.databaseName,
      description: 'Name of the database the application connects to',
      exportName: `${exportPrefix}-db-name`,
    });

    new CfnOutput(this, 'CredentialsSecretArn', {
      value: this.credentialsSecret.secretArn,
      description: `ARN of the Secrets Manager secret holding the credentials of ${namePrefix}`,
      exportName: `${exportPrefix}-db-secret-arn`,
    });
  }
}
