-- The products table.
--
-- Flyway owns the schema: this file is the only place a table is created, and it is applied once,
-- in order, and recorded in flyway_schema_history. Hibernate is configured to validate against it
-- rather than to create it, so a mismatch between this SQL and the Product entity stops the
-- application at startup instead of corrupting data later.
--
-- Types are chosen to match the entity mapping exactly:
--   id          BIGINT identity, assigned by the database (GenerationType.IDENTITY)
--   name        VARCHAR(255)   NOT NULL   - @Column(nullable = false), default length
--   description VARCHAR(1000)  NULL       - @Column(length = 1000)
--   price       NUMERIC(12, 2) NOT NULL   - BigDecimal with precision 12, scale 2 (never a double)
--   quantity    INTEGER        NOT NULL   - @Column(nullable = false), defaults to 0
--   created_at  TIMESTAMPTZ    NOT NULL   - Instant, set by @PrePersist
--   updated_at  TIMESTAMPTZ    NOT NULL   - Instant, set by @PrePersist and @PreUpdate
--
-- The timestamps are `timestamptz`, not `timestamp`: an Instant is an absolute point in time, and
-- the column that stores it should not depend on the reader's zone. `timestamp` would silently
-- shift the value whenever the JVM's default zone changed.
CREATE TABLE products (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255)    NOT NULL,
    description VARCHAR(1000),
    price       NUMERIC(12, 2)  NOT NULL,
    quantity    INTEGER         NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ     NOT NULL,
    updated_at  TIMESTAMPTZ     NOT NULL
);

-- Products are listed and fetched by id, and the table is expected to grow, so the primary key is
-- the only index needed for this phase. A search index belongs here as a new migration when a later
-- phase adds filtering.
