import { RemovalPolicy } from 'aws-cdk-lib';
import { InstanceType } from 'aws-cdk-lib/aws-ec2';
import { RetentionDays } from 'aws-cdk-lib/aws-logs';
import { PostgresEngineVersion } from 'aws-cdk-lib/aws-rds';

/**
 * Environments this application can be deployed to. The name selects which configuration
 * file in `lib/config` is used and is applied to every resource as a tag.
 */
export type EnvironmentName = 'dev' | 'uat' | 'prod';

export const ENVIRONMENT_NAMES: readonly EnvironmentName[] = ['dev', 'uat', 'prod'];

export function isEnvironmentName(value: string): value is EnvironmentName {
  return (ENVIRONMENT_NAMES as readonly string[]).includes(value);
}

/**
 * VPC Flow Logs are optional because they are billed per GB ingested. They are enabled in the
 * environments where an audit trail of network traffic is worth that cost.
 */
export interface FlowLogsConfig {
  readonly enabled: boolean;
  /** How long flow log events are kept in CloudWatch Logs. */
  readonly retention: RetentionDays;
}

/**
 * Runtime configuration of the containerised application tier (Phase 2).
 *
 * Everything the ECS service, the Fargate task definition and the load balancer need is expressed
 * here, so that no stack contains an environment specific value and the task sizing is a reviewable
 * configuration decision rather than a magic number buried in a construct.
 */
export interface ApplicationConfig {
  /**
   * Number of Fargate tasks the ECS service keeps running. Phase 2 fixes this at 1 everywhere;
   * auto scaling, which varies it at runtime, is a later phase.
   */
  readonly desiredCount: number;

  /** Fargate task CPU units (1024 units = 1 vCPU). Must form a valid Fargate cpu/memory pair. */
  readonly cpu: number;

  /** Fargate task memory in MiB. Must form a valid Fargate cpu/memory pair. */
  readonly memoryLimitMiB: number;

  /** Port the Spring Boot API listens on inside the container. */
  readonly containerPort: number;

  /** Target group health check path, served by Spring Boot Actuator. */
  readonly healthCheckPath: string;

  /**
   * Container image tag the ECS task definition deploys.
   *
   * Only immutable tags belong here: the tag is baked into the task definition, and a mutable tag
   * such as `latest` would make a task replacement deploy a different image than the one reviewed.
   * `resolveImageTag()` rejects `latest` outright. The value can be overridden at deploy time with
   * `-c imageTag=<tag>` or the `IMAGE_TAG` environment variable.
   */
  readonly imageTag: string;

  /** How long ECS container logs are kept in CloudWatch Logs. */
  readonly logRetention: RetentionDays;
}

/**
 * Runtime configuration of the relational data tier (Phase 3).
 *
 * The application tier above is stateless and can be replaced at any moment; the database cannot.
 * Every value that decides how much data can be lost, how long it survives a mistake, and how much
 * it costs is therefore expressed here per environment instead of being buried in the database
 * stack, so the difference between dev, uat and prod is a reviewable diff of this file.
 *
 * Deliberately absent: any username or password. The master password is generated by AWS Secrets
 * Manager at deploy time (see the database stack), never written down here or anywhere else.
 */
export interface DatabaseConfig {
  /**
   * Name of the initial database created inside the instance. The application connects to this
   * database, not to the engine's default one.
   */
  readonly databaseName: string;

  /**
   * Master user name. RDS reserves a handful of names (`postgres`, `admin`, `rdsadmin`, ...), which
   * the configuration validator rejects.
   *
   * Only the user name lives here; the password is generated by Secrets Manager. It is passed to the
   * instance as a plain user name (not a dynamic secret reference) so rotating the secret replaces
   * the password without replacing the instance.
   */
  readonly masterUsername: string;

  /**
   * PostgreSQL engine version. Pinned to a major version on purpose: RDS then runs the current
   * minor release of that major and applies minor upgrades during the maintenance window, while a
   * major upgrade - which can break compatibility - remains an explicit, reviewed change.
   */
  readonly engineVersion: PostgresEngineVersion;

  /**
   * Instance class, for example `db.t4g.micro`. Burstable, Graviton based classes are the cheapest
   * valid choice for this workload; a later phase right-sizes them from real metrics.
   */
  readonly instanceType: InstanceType;

  /** Allocated storage in GiB. The gp3 minimum is 20; storage is encrypted with the RDS KMS key. */
  readonly allocatedStorageGb: number;

  /**
   * Days automated backups are retained, 0 to 35. 0 disables automated backups and is deliberately
   * not used by any environment: the recovery window is the whole point of running a managed
   * database.
   */
  readonly backupRetentionDays: number;

  /**
   * Deploy a synchronously replicated standby in a second Availability Zone. Doubles the instance
   * cost and halves the failover time. It is the database's answer to an AZ failure, which is why
   * production enables it and dev does not.
   */
  readonly multiAz: boolean;

  /**
   * Refuse to delete the instance until this is switched off. Independent of `removalPolicy`: it
   * guards against a person or a pipeline deleting the instance, while the removal policy decides
   * what CloudFormation does with the instance when the stack itself is deleted.
   */
  readonly deletionProtection: boolean;

  /**
   * What CloudFormation does with the instance and its credentials secret when the stack is deleted.
   * `DESTROY` is only appropriate where the data is genuinely disposable.
   */
  readonly removalPolicy: RemovalPolicy;
}

/**
 * Public DNS and TLS configuration of the platform (Phase 3.5).
 *
 * The platform owns a *subdomain* rather than the apex domain. A registrar can only delegate a
 * whole zone, so the domain's registrar keeps NS records for `dev.example.com` that point at the
 * four name servers of the Route 53 hosted zone this configuration names. Route 53 then answers
 * every name underneath that subdomain, and the certificate's DNS validation record is created
 * inside it automatically. Nothing is ever looked up: the zone is created, not imported.
 *
 * DNS is optional because dev still needs to synthesise and deploy HTTP-only when no domain has
 * been delegated yet. It is not optional in production: plaintext HTTP is not a production option,
 * so the configuration validator refuses a production environment without a `dns` block.
 */
export interface DnsConfig {
  /**
   * Name of the delegated subdomain, for example `dev.example.com`. Route 53 creates a public
   * hosted zone for exactly this name; the registrar's NS records must point at the name servers
   * the zone exports before the certificate can finish validating.
   */
  readonly zoneName: string;

  /** Leftmost label the API answers on inside the zone, for example `api` for `api.dev.example.com`. */
  readonly apiSubdomain: string;
}

/**
 * Everything a stack needs to know about the environment it is deployed to.
 *
 * Values are supplied per environment (see `dev.ts`, `uat.ts`, `prod.ts`) so that no stack ever
 * contains environment specific values. This interface must never carry secrets: account ids and
 * regions are identifiers, not credentials, and credentials are resolved by the CDK CLI from the
 * active profile/role at deploy time.
 */
export interface EnvironmentConfig {
  /** Short environment identifier, used for tags, resource names and stack names. */
  readonly environment: EnvironmentName;

  /**
   * Target AWS account, read from the `ECOMMERCE_<ENV>_ACCOUNT` environment variable (see the
   * README for how to set it on PowerShell and bash).
   *
   * Left undefined by default, which makes the stack environment-agnostic: the CDK CLI then resolves
   * the account from the active credentials at deploy time, account ids never end up in source
   * control, and `cdk synth` works without credentials. Pin it per environment before deploying
   * anything other than dev, so `-c environment=prod` cannot target whichever account the current
   * credentials happen to resolve to.
   */
  readonly account?: string;

  /** Target AWS region. */
  readonly region: string;

  /** IPv4 CIDR block of the VPC. Must not overlap with the other environments. */
  readonly vpcCidr: string;

  /** Number of Availability Zones to spread the subnets over. */
  readonly maxAzs: number;

  /**
   * Number of NAT Gateways. 1 is cheap but not AZ redundant, one per Availability Zone is
   * resilient but costs more. 0 disables outbound internet access for private subnets.
   */
  readonly natGateways: number;

  /** Removal policy for resources that support one, such as the flow log group. */
  readonly removalPolicy: RemovalPolicy;

  /** VPC Flow Logs configuration. */
  readonly flowLogs: FlowLogsConfig;

  /** Containerised application tier configuration (Phase 2). */
  readonly application: ApplicationConfig;

  /** Relational data tier configuration (Phase 3). */
  readonly database: DatabaseConfig;

  /**
   * Public DNS and TLS configuration (Phase 3.5). Omitted in dev until a domain has been delegated,
   * which keeps `cdk synth` and an HTTP-only deployment working; required in production.
   */
  readonly dns?: DnsConfig;
}
